/**
 * Seeded Physics Studio answers.
 *
 * The demo starts with eight teacher-verified answers making up the library,
 * two waiting in the review queue, and two still labelled AI-assisted because
 * nobody asked for a review — so the whole provenance pipeline is visible
 * without anyone having to click through it first.
 *
 * The physics is genuine Cambridge 9702 material; the students and the dates
 * are not. `live: false` on every seed is honest: a script wrote them, not a
 * model.
 */
import type { StudioAnswer } from "@/lib/domain/physics";
import { daysAgoISO } from "@/lib/utils";
import { PHYSICS_CLASS_ID, PHYSICS_TEACHER_ID } from "./cohort";

const TEACHER_NAME = "Mr. Usman Tariq";

export const SEED_ANSWERS: StudioAnswer[] = [
  {
    id: "pa-seed-01",
    slug: "why-does-a-satellite-in-a-higher-orbit-move-more-slowly-01",
    studentId: "s-ali-hamza",
    studentName: "Ali Hamza",
    classId: PHYSICS_CLASS_ID,
    topic: "Gravitational fields",
    mode: "examiner",
    question: "Why does a satellite in a higher orbit move more slowly, when it has more energy?",
    answer: {
      idea: "Orbital speed is fixed by the radius alone: gravity supplies the centripetal force, which gives v = √(GM/r). More total energy and less speed are not in conflict, because the extra energy sits in the potential store.",
      steps: [
        "M1 — method: gravity provides the centripetal force, so GMm/r² = mv²/r. The satellite's own mass cancels, which is why orbital speed never depends on it.",
        "M1 — working: rearranging gives v² = GM/r, so v = √(GM/r). A larger r therefore means a smaller v.",
        "A1 — answer: the higher satellite is slower, and by v = 2πr/T with a larger r and a smaller v, its period is longer on both counts.",
        "B1 — quality: for the energy, total orbital energy is Eₖ + Eₚ = GMm/2r − GMm/r = −GMm/2r. Raising r makes this less negative, so the total energy is larger even though Eₖ = GMm/2r has fallen.",
        "The examiner is looking for the words 'gravitational force provides the centripetal force' before any algebra. That sentence alone is the first mark.",
      ],
      pitfall: "Answering that the higher satellite is slower because gravity is weaker, and stopping there. Gravity is weaker, but the mark is for showing that the required centripetal force falls faster than the available force does — that is what v = √(GM/r) encodes.",
      check: "Write down the total energy of an orbit at 2r and at r. Which is larger, and which has the greater kinetic energy?",
    },
    status: "teacher-verified",
    live: false,
    askedAt: daysAgoISO(24),
    reviewedAt: daysAgoISO(23),
    reviewerId: PHYSICS_TEACHER_ID,
    reviewerName: TEACHER_NAME,
    reviewNote: "Correct and complete. The energy half is what separates a grade A from a B here — most of the class stops at v = √(GM/r) and never addresses the premise of the question.",
    inLibrary: true,
  },
  {
    id: "pa-seed-02",
    slug: "difference-between-emf-and-potential-difference-02",
    studentId: "s-sana-khalid",
    studentName: "Sana Khalid",
    classId: PHYSICS_CLASS_ID,
    topic: "D.C. circuits",
    mode: "worked-example",
    question: "What is the actual difference between e.m.f. and potential difference? They both seem to be measured in volts.",
    answer: {
      idea: "Both are energy per unit charge, so both are in volts. E.m.f. is energy converted into electrical form per coulomb; potential difference is electrical energy converted into some other form per coulomb.",
      steps: [
        "Start from the definition of each: e.m.f. ε = W/Q where W is the energy a source converts into electrical energy; p.d. V = W/Q where W is the energy a component converts out of electrical energy.",
        "So a cell has an e.m.f. and a resistor has a p.d. across it. A source is the only place an e.m.f. arises.",
        "Worked example: a cell of e.m.f. 1.5 V and internal resistance 0.50 Ω drives a current of 0.60 A. The cell converts 1.5 J of chemical energy per coulomb.",
        "Of that, Ir = 0.60 × 0.50 = 0.30 J per coulomb is dissipated inside the cell itself, as internal energy.",
        "The terminal p.d. is what is left for the external circuit: V = ε − Ir = 1.5 − 0.30 = 1.2 V.",
        "Now apply it to your own question: the moment a current flows, the reading on a voltmeter across the terminals is the p.d., not the e.m.f. You only measure the e.m.f. directly when the current is zero.",
      ],
      pitfall: "Writing that e.m.f. is 'the voltage of the battery'. That phrasing earns nothing, and it hides the reason a terminal p.d. drops when the current rises.",
      check: "How would you measure the e.m.f. of a cell experimentally, and why does the answer involve making the current as close to zero as possible?",
    },
    status: "teacher-verified",
    live: false,
    askedAt: daysAgoISO(21),
    reviewedAt: daysAgoISO(20),
    reviewerId: PHYSICS_TEACHER_ID,
    reviewerName: TEACHER_NAME,
    reviewNote: "Verified. Learn the two definitions word for word — 9702 asks you to define both, and 'energy per unit charge' without saying which way the conversion goes scores zero.",
    inLibrary: true,
  },
  {
    id: "pa-seed-03",
    slug: "why-is-kinetic-energy-not-conserved-when-trolleys-stick-03",
    studentId: "s-daniyal-butt",
    studentName: "Daniyal Butt",
    classId: PHYSICS_CLASS_ID,
    topic: "Dynamics",
    mode: "hint",
    question: "If momentum is always conserved in a collision, why is kinetic energy not?",
    answer: {
      idea: "Momentum conservation follows from Newton's third law, which holds in every collision. Kinetic energy conservation is an extra condition that only perfectly elastic collisions happen to satisfy.",
      steps: [
        "During the collision the two bodies push on each other with equal and opposite forces, for exactly the same length of time.",
        "So the impulses are equal and opposite, the momentum changes are equal and opposite, and the total is unchanged — whatever the bodies are made of.",
        "Now ask what the bodies are made of. If they deform, or warm up, or make a sound, energy has left the kinetic store. Nothing in Newton's third law prevents that.",
        "Try the next step yourself: take two trolleys of 2.0 kg at 3.0 m s⁻¹ and 1.0 kg at rest that stick together. Find the common velocity from momentum, then compare total kinetic energy before and after. Paste your two numbers and I will tell you whether your reasoning is sound.",
      ],
      pitfall: "Saying kinetic energy is 'lost'. It is transferred — to internal energy in the deformed bodies and to sound. Total energy is conserved in every collision; it is only the kinetic share that falls.",
      check: "For your two trolleys, what fraction of the original kinetic energy survived, and where did the rest go?",
    },
    status: "teacher-verified",
    live: false,
    askedAt: daysAgoISO(18),
    reviewedAt: daysAgoISO(17),
    reviewerId: PHYSICS_TEACHER_ID,
    reviewerName: TEACHER_NAME,
    reviewNote: "Good. Add one line for the exam: in a perfectly elastic collision the relative speed of approach equals the relative speed of separation. That is the testable statement examiners want.",
    inLibrary: true,
  },
  {
    id: "pa-seed-04",
    slug: "why-does-brighter-light-not-release-electrons-04",
    studentId: "s-hafsa-tariq",
    studentName: "Hafsa Tariq",
    classId: PHYSICS_CLASS_ID,
    topic: "Quantum physics",
    mode: "examiner",
    question: "Why does making the light brighter never release photoelectrons if the frequency is too low?",
    answer: {
      idea: "Energy arrives in indivisible photons of hf, and one photon interacts with one electron. Brightness changes how many photons arrive per second, never how much energy each one carries.",
      steps: [
        "M1 — method: state the one-to-one interaction. A single photon delivers all of its energy hf to a single electron, and an electron cannot accumulate energy from several photons.",
        "M1 — working: for the electron to escape, that single photon must supply at least the work function Φ, the minimum energy needed to remove an electron from the surface.",
        "A1 — answer: so emission requires hf ≥ Φ, giving a threshold frequency f₀ = Φ/h. Below f₀ no photon has enough energy, so no electron escapes at any intensity.",
        "B1 — quality: doubling the intensity doubles the photon arrival rate, so above f₀ it doubles the photocurrent — but it leaves the maximum kinetic energy ½mv²max = hf − Φ completely unchanged.",
        "Examiners award the first mark for the one photon, one electron statement. Answers that argue only from 'the energy is too small' without saying why it cannot add up lose it.",
      ],
      pitfall: "Arguing from intensity. Intensity is photons per second; frequency is joules per photon. The whole photoelectric effect is the experimental proof that those are different quantities.",
      check: "Sketch maximum kinetic energy against frequency. What are the gradient and the two intercepts, and which one is the work function?",
    },
    status: "teacher-verified",
    live: false,
    askedAt: daysAgoISO(15),
    reviewedAt: daysAgoISO(14),
    reviewerId: PHYSICS_TEACHER_ID,
    reviewerName: TEACHER_NAME,
    reviewNote: "Verified. This is the single most-asked 9702 explain question. Learn the graph in the last line — gradient h, x-intercept f₀, y-intercept −Φ.",
    inLibrary: true,
  },
  {
    id: "pa-seed-05",
    slug: "how-do-i-know-which-way-the-induced-current-flows-05",
    studentId: "s-rayyan-malik",
    studentName: "Rayyan Malik",
    classId: PHYSICS_CLASS_ID,
    topic: "Magnetic fields",
    mode: "hint",
    question: "How do I work out which way an induced current flows? I keep guessing.",
    answer: {
      idea: "Lenz's law decides it: the induced current always flows so as to oppose the change that produced it. Work out what is changing first, and the direction follows.",
      steps: [
        "Say out loud what is changing. Is the flux through the loop increasing or decreasing? Nothing else matters yet.",
        "The induced current opposes that change, so it creates a magnetic field that tries to keep the flux as it was: opposing the increase, or propping up the decrease.",
        "Use the right-hand grip rule on the coil to turn the field direction you need into a current direction around the loop.",
        "Now try it on yours and tell me your two answers: is the flux rising or falling, and which way must the induced field point? I will check the reasoning before you commit to a current direction.",
      ],
      pitfall: "Reaching for Fleming's rules first. The left hand is for the motor effect, where current is the cause; here current is the effect, so Lenz decides the direction and the right-hand rule only converts it.",
      check: "A magnet is dropped north pole first through a copper ring. Which way does the current flow as it approaches, and does the ring push or pull it?",
    },
    status: "teacher-verified",
    live: false,
    askedAt: daysAgoISO(12),
    reviewedAt: daysAgoISO(11),
    reviewerId: PHYSICS_TEACHER_ID,
    reviewerName: TEACHER_NAME,
    reviewNote: "Exactly the order I want: what is changing, then oppose it, then grip rule. Lenz's law is conservation of energy in disguise — say that if the question asks you to justify it.",
    inLibrary: true,
  },
  {
    id: "pa-seed-06",
    slug: "why-is-the-rms-value-used-instead-of-the-peak-06",
    studentId: "s-zoya-imran",
    studentName: "Zoya Imran",
    classId: PHYSICS_CLASS_ID,
    topic: "Alternating currents",
    mode: "worked-example",
    question: "Why do we quote the r.m.s. value of an alternating current rather than the peak or the average?",
    answer: {
      idea: "The average of a symmetrical alternating current over a whole cycle is zero, which tells you nothing. The r.m.s. value is defined so that it does the one job that matters: it predicts the heating.",
      steps: [
        "Power in a resistor is P = I²R, and squaring removes the sign, so the current heats the resistor on both halves of the cycle.",
        "The mean of I² over a cycle is therefore what sets the mean power — not the mean of I, which is zero.",
        "Define Irms as the square root of that mean: the steady direct current that would dissipate the same mean power in the same resistor.",
        "For a sinusoid this works out as Irms = I₀/√2, and likewise Vrms = V₀/√2.",
        "Worked example: a mains supply quoted as 230 V has a peak of V₀ = 230 × √2 ≈ 325 V. Mean power into a 100 Ω heater is Vrms²/R = 230²/100 = 529 W.",
        "Now apply it to yours: whenever a question gives you a voltage without saying which it is, it means r.m.s. If it gives you a peak, divide by √2 before any power calculation.",
      ],
      pitfall: "Putting peak values into a power formula. That overstates the mean power by a factor of two, and it is the single most common slip on this topic.",
      check: "Insulation in a 230 V circuit has to withstand what voltage, and why is that not 230 V?",
    },
    status: "teacher-verified",
    live: false,
    askedAt: daysAgoISO(9),
    reviewedAt: daysAgoISO(8),
    reviewerId: PHYSICS_TEACHER_ID,
    reviewerName: TEACHER_NAME,
    reviewNote: "Verified. The last check is a real exam question and almost nobody gets it: the insulation has to survive 325 V, not 230 V.",
    inLibrary: true,
  },
  {
    id: "pa-seed-07",
    slug: "why-is-gravitational-potential-negative-07",
    studentId: "s-eman-siddiqui",
    studentName: "Eman Siddiqui",
    classId: PHYSICS_CLASS_ID,
    topic: "Gravitational fields",
    mode: "examiner",
    question: "Why is gravitational potential always negative? It looks like a sign error.",
    answer: {
      idea: "It is a choice of zero, not an error. Potential is defined as zero at infinity, and since gravity always attracts, every point closer than infinity has less potential energy than that.",
      steps: [
        "M1 — method: define the quantity properly. Gravitational potential at a point is the work done per unit mass in bringing a small test mass from infinity to that point.",
        "M1 — working: gravity is always attractive, so moving the test mass inward means the field does the work, not you. The work done per unit mass is therefore negative.",
        "A1 — answer: hence φ = −GM/r, which is negative everywhere and rises toward zero as r increases.",
        "B1 — quality: the consequence is that escaping to infinity requires you to supply energy, giving escape speed from ½mv² = GMm/r, so v = √(2GM/r).",
        "Examiners want 'zero at infinity' stated explicitly. Without it, the negative sign looks arbitrary and the definition mark is not awarded.",
      ],
      pitfall: "Quoting φ = GM/r without the minus, then concluding that a satellite gains potential energy as it falls. Every sign in the energy argument then comes out backwards.",
      check: "Between the Earth's surface and a point twice the Earth's radius from the centre, does the potential increase or decrease, and does an object gain or lose potential energy moving outward?",
    },
    status: "teacher-verified",
    live: false,
    askedAt: daysAgoISO(6),
    reviewedAt: daysAgoISO(5),
    reviewerId: PHYSICS_TEACHER_ID,
    reviewerName: TEACHER_NAME,
    reviewNote: "Verified. Eleven of you dropped the minus sign in the mock. Write 'zero at infinity' into the definition every single time.",
    inLibrary: true,
  },
  {
    id: "pa-seed-08",
    slug: "why-does-fringe-spacing-increase-with-screen-distance-08",
    studentId: "s-shayan-ali",
    studentName: "Shayan Ali",
    classId: PHYSICS_CLASS_ID,
    topic: "Superposition",
    mode: "hint",
    question: "Why do the fringes get further apart when I move the screen back in a double-slit experiment?",
    answer: {
      idea: "The fringes are fixed directions, not fixed positions. Each maximum leaves the slits at its own angle, so the further the screen, the further apart those directions have spread by the time they land.",
      steps: [
        "Think in angles first. The first maximum sits where the path difference is one wavelength, which fixes an angle θ with sin θ = λ/a. Moving the screen does not change that angle.",
        "On a screen a distance D away, that direction arrives at x ≈ Dθ. Doubling D doubles x.",
        "That is exactly what λ = ax/D says, rearranged as x = λD/a — so x rises with D and falls with the slit separation a.",
        "Now predict before you measure: what happens to the spacing if you keep D fixed and halve a instead? Tell me your prediction and the reasoning, and I will check it before you set the apparatus up.",
      ],
      pitfall: "Swapping a and x in λ = ax/D. a is the slit separation, x is the fringe spacing on the screen. Label both on your diagram before you substitute anything.",
      check: "Which of the three — λ, a or D — would you change to make the fringes easiest to measure accurately, and why?",
    },
    status: "teacher-verified",
    live: false,
    askedAt: daysAgoISO(4),
    reviewedAt: daysAgoISO(3),
    reviewerId: PHYSICS_TEACHER_ID,
    reviewerName: TEACHER_NAME,
    reviewNote: "Verified. Thinking in angles first is the right habit — it is also what makes the diffraction grating equation obvious later.",
    inLibrary: true,
  },

  /* ---- Waiting on the teacher: in the review queue, not in the library ---- */
  {
    id: "pa-seed-09",
    slug: "why-does-a-capacitor-discharge-exponentially-09",
    studentId: "s-owais-qadir",
    studentName: "Owais Qadir",
    classId: PHYSICS_CLASS_ID,
    topic: "Capacitance",
    mode: "worked-example",
    question: "Why is capacitor discharge exponential rather than a straight line?",
    answer: {
      idea: "Whenever the rate at which a quantity falls is proportional to how much of it is left, the decay is exponential. A discharging capacitor is the standard example.",
      steps: [
        "The charge left on the plates sets the p.d.: V = Q/C.",
        "That p.d. drives the current through the resistor: I = V/R = Q/RC.",
        "But the current is the rate at which charge is leaving, so the rate of loss is proportional to the charge remaining. Less charge means a smaller current means a slower loss.",
        "A straight line would need a constant current, which would need a constant p.d., which would need the charge not to fall — a contradiction.",
        "Solving gives Q = Q₀e^(−t/RC), with the time constant τ = RC: the time to fall to 1/e, about 37%, of the starting value.",
        "Now try yours: a 2200 μF capacitor discharges through 10 kΩ. Find τ, then the charge remaining after one and after two time constants.",
      ],
      pitfall: "Reading the time constant as the time to reach zero. It never reaches zero; τ is the time to fall to 37%, and after 5τ it is under 1%.",
      check: "For your 2200 μF and 10 kΩ, what is τ, and how long until the p.d. has fallen below 1% of its starting value?",
    },
    status: "review-requested",
    live: false,
    askedAt: daysAgoISO(2),
    inLibrary: false,
  },
  {
    id: "pa-seed-10",
    slug: "what-is-the-unit-of-the-decay-constant-10",
    studentId: "s-laiba-noor",
    studentName: "Laiba Noor",
    classId: PHYSICS_CLASS_ID,
    topic: "Nuclear physics",
    mode: "hint",
    question: "What exactly is the decay constant, and why is its unit s⁻¹?",
    answer: {
      idea: "The decay constant is the probability per unit time that any one nucleus decays. A probability is a pure number, so per unit time makes the unit s⁻¹.",
      steps: [
        "Start from what it multiplies: activity A = λN, where N is the number of undecayed nuclei.",
        "Activity is decays per second, so λ = A/N has units of (per second) divided by (a pure count) — that is s⁻¹.",
        "Read it physically: λ = 0.02 s⁻¹ means each surviving nucleus has about a 2% chance of decaying in the next second, regardless of how long it has already survived.",
        "Take the next step yourself: use λ = ln2/t½ to find λ for a source with a half-life of 6.0 hours, and give it in s⁻¹. Show me the conversion as well as the number.",
      ],
      pitfall: "Treating λ as a lifetime. It is a rate, so a large λ means fast decay and a short half-life — the inverse of what the word 'constant' suggests.",
      check: "Two sources have λ = 0.02 s⁻¹ and λ = 0.2 s⁻¹. Which has the longer half-life, and by what factor?",
    },
    status: "review-requested",
    live: false,
    askedAt: daysAgoISO(1),
    inLibrary: false,
  },

  /* ---- Never sent for review: still labelled AI-assisted ---- */
  {
    id: "pa-seed-11",
    slug: "why-do-gas-laws-need-kelvin-11",
    studentId: "s-ali-hamza",
    studentName: "Ali Hamza",
    classId: PHYSICS_CLASS_ID,
    topic: "Ideal gases",
    mode: "hint",
    question: "Why do the gas laws insist on kelvin instead of degrees Celsius?",
    answer: {
      idea: "The gas laws contain ratios of temperature, and a ratio only means something on a scale whose zero is a real zero. Celsius has an arbitrary zero; kelvin does not.",
      steps: [
        "Look at where T appears: pV = nRT, and p₁V₁/T₁ = p₂V₂/T₂. Both use T as a multiplier or in a ratio.",
        "On the kelvin scale, zero means zero molecular kinetic energy, so doubling T genuinely doubles the mean kinetic energy.",
        "On the Celsius scale, zero is the freezing point of water, chosen by convention. Going from 1 °C to 2 °C is not a doubling of anything physical.",
        "Take the next line yourself: work out the ratio for a gas heated from 27 °C to 54 °C, first in Celsius and then in kelvin. The two answers will not agree, and one of them is meaningless — tell me which and why.",
      ],
      pitfall: "Converting only one of the two temperatures in a ratio. Both must be in kelvin, or the ratio is wrong even though each number looks converted.",
      check: "For 27 °C to 54 °C, what is the true ratio of the absolute temperatures, and by what percentage does the pressure actually rise at constant volume?",
    },
    status: "ai-assisted",
    live: false,
    askedAt: daysAgoISO(7),
    inLibrary: false,
  },
  {
    id: "pa-seed-12",
    slug: "what-makes-a-motion-simple-harmonic-12",
    studentId: "s-zoya-imran",
    studentName: "Zoya Imran",
    classId: PHYSICS_CLASS_ID,
    topic: "Oscillations",
    mode: "hint",
    question: "How do I tell whether an oscillation is actually simple harmonic?",
    answer: {
      idea: "One test decides it: a = −ω²x. Acceleration proportional to displacement, and always directed back toward equilibrium.",
      steps: [
        "Find the resultant force on the body when it is displaced by x from equilibrium.",
        "If that force comes out proportional to x and pointing back toward equilibrium, divide by the mass and you have a = −ω²x, so the motion is simple harmonic.",
        "Read ω² off as the constant of proportionality, then get the period from T = 2π/ω.",
        "Try it on a mass on a spring: the extra force when displaced by x is −kx, so a = −(k/m)x. What is ω², and therefore what is T?",
      ],
      pitfall: "Assuming every back-and-forth motion is simple harmonic. A ball bouncing on the floor oscillates and is not, because the force is not proportional to displacement.",
      check: "A simple pendulum is only approximately simple harmonic. At what point in the derivation does the approximation enter, and when does it break down?",
    },
    status: "ai-assisted",
    live: false,
    askedAt: daysAgoISO(3),
    inLibrary: false,
  },
];
